services:
 mysql_2:
    image: mysql     
    ports:
     - "3306:3306"
    expose:
     - "3306"
    environment:
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=portal_noticias
      - MYSQL_ROOT_PASSWORD=1234
      
    volumes:
      - db_data_portal_noticias:/var/lib/mysql_portal_noticias
    
volumes:
 db_data_portal_noticias: